name: Deployment pipeline

on:
  push:
    branches:
      - source
  pull_request:
    branches: [source]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: deploy to heroku
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }} # this won't deploy if the commit message has #skip in it and if the commit doesn't happen from PR
        uses: akhileshns/heroku-deploy@v3.7.8 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: pipeline-test12 # Must be unique in Heroku
          heroku_email: yousif.abozid@yahoo.com
          healthcheck: https://pipeline-test12.herokuapp.com/version
          checkstring: 1
          delay: 5 # to ensure that heroku is ready for health check after the deployment
          rollbackonhealthcheckfailed: true # to roll back to the previous version if the health check fails
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }} # this won't add version tag if the commit message has #skip in it and if the commit doesn't happen from PR
        uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true # to add letter v before version number
          DRY_RUN: false # if true it will print in the console next version number without creating or tagging the release!
          DEFAULT_BUMP: patch # to choose between major, minor or patch